AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Returns your after tax income as well as the amounts you pay for each form of tax
Resources:
  main:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
